---

# Provision the infrastructure using Terraform
- name: Provision infrastructure
  hosts: openstack
  pre_tasks:
    - name: Check that Notebook repository URL exists 
      uri:
        url: "{{ cluster_repository }}"
  roles:
    - cluster_infra
  post_tasks:
    - name: Wait for Jupyter notebook to become available
      uri:
        url: "http://{{ zenith_fqdn_repo2docker }}"
        method: GET
        follow_redirects: safe
      register: repo2docker_uri
      changed_when: false
      failed_when: repo2docker_uri.status >= 500
      retries: 180
      delay: 10
      # 404 and 503 are the statuses that are seen when the Zenith service is not ready yet
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      until: repo2docker_uri.status not in [404, 503, -1]
      when: (cluster_state | default('present')) == 'present'
