---

# Provision the infrastructure using Terraform
- name: Provision infrastructure
  hosts: openstack
  pre_tasks:
    - name: Check that Notebook repository URL exists 
      uri:
        url: "{{ cluster_repository }}"
      when: (cluster_state | default('present')) == 'present'
  roles:
    - cluster_infra
  post_tasks:
    - name: Wait for RStudio to become available
      uri:
        url: "http://{{ zenith_fqdn_rstudio }}"
        method: GET
        follow_redirects: safe
      register: rstudio_uri
      changed_when: false
      failed_when: >-
        rstudio_uri.status < 0 or
        rstudio_uri.status == 404 or
        rstudio_uri.status >= 500
      retries: 180
      delay: 10
      # 404 and 503 are the statuses that are seen when the Zenith service is not ready yet
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      until: rstudio_uri.status not in [404, 503, -1]
      when: (cluster_state | default('present')) == 'present'
    
    - name: Wait for Monitoring to become available
      uri:
        url: "http://{{ zenith_fqdn_monitoring }}"
        method: GET
        follow_redirects: safe
      register: monitoring_uri
      changed_when: false
      failed_when: >-
        monitoring_uri.status < 0 or
        monitoring_uri.status == 404 or
        monitoring_uri.status >= 500
      retries: 180
      delay: 10
      # 404 and 503 are the statuses that are seen when the Zenith service is not ready yet
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      until: monitoring_uri.status not in [404, 503, -1]
      when: (cluster_state | default('present')) == 'present'
