# The path to the Terraform binary, if not in the PATH
terraform_binary_path:

# By default, provision the infrastructure rather than tear it down
terraform_state: present

# Default to the local backend if not otherwise specified
terraform_backend_type: local
# The backend configuration to use
terraform_backend_config: {}
# The variables to use when invoking Terraform
terraform_variables: {}
